// <auto-generated />
namespace Couponat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addStoreTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStoreTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202106150806044_addStoreTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
